### ISSUE TITLE
Py2exe

### ISSUE THREAD

**Issue by 3dgoose** [georgenicolaou/androidlockcracker#5]
Hi, I used py2exe on python 2.7 to make it as an executable(.exe)

It opens but automatically close

**Comment by TheCatGuy12321** [comment]
maybe you have to run it in a console or you didn't specify the flags(e.g. --help)?

**Comment by 3dgoose** [comment]
> maybe you have to run it in a console or you didn't specify the flags(e.g. --help)? 

Thx bro. It works.
